### ISSUE TITLE
the weight between nodes in graph

### ISSUE THREAD

**Issue by lytum** [Wluper/Retrograph#15]
Thanks for your work and sharing.

May I ask you why you set the weight between nodes is always 1? --> refer to the code: "G[edge[0]][edge[1]]['weight'] = 1" in random_walks.py script.

And may I ask you what the 'alias' means in random_walks.py?

And what does 'p' and 'q' mean in random_walks.py?

Thanks in advance!

**Comment by anlausch** [comment]
Even though conceptnet provides weights for the assertions (i.e., weights on edges), they do not seem to be assigned with  high confidence (https://github.com/commonsense/conceptnet5/issues/152). This is why, here, we go for the most general case and weight each assertion equally to not erroneously bias the random walks.
For documentation about the hyper parameters, please check the original Node2Vec code. Thanks!
